/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Practice;

import org.opensourcephysics.controls.CalculationControl;
import org.opensourcephysics.controls.SimulationControl;

/**
 *
 * @author Jay C Espinoza
 */
public class OriginalsMenu extends javax.swing.JFrame {

    /**
     * Creates new form OriginalsMenu
     */
    public OriginalsMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        oEFieldButton = new javax.swing.JButton();
        mEFieldButton = new javax.swing.JButton();
        oEFLineButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Elige una Applet");

        oEFieldButton.setText("Original ElectricFieldApp");
        oEFieldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oEFieldButtonActionPerformed(evt);
            }
        });

        mEFieldButton.setText("Our ElectricFieldApp 10.1 b");
        mEFieldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEFieldButtonActionPerformed(evt);
            }
        });

        oEFLineButton.setText("Original ElectricFieldLineApp");
        oEFLineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oEFLineButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(oEFieldButton)
                        .addGap(37, 37, 37)
                        .addComponent(mEFieldButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(oEFLineButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oEFieldButton)
                    .addComponent(mEFieldButton))
                .addGap(81, 81, 81)
                .addComponent(oEFLineButton)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mEFieldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEFieldButtonActionPerformed
        SimulationControl.createApp(new EFApp2());
    }//GEN-LAST:event_mEFieldButtonActionPerformed

    private void oEFieldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oEFieldButtonActionPerformed
        CalculationControl.createApp(new ElectricFieldApp());
    }//GEN-LAST:event_oEFieldButtonActionPerformed

    private void oEFLineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oEFLineButtonActionPerformed
        CalculationControl.createApp(new FieldLineApp());
    }//GEN-LAST:event_oEFLineButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OriginalsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OriginalsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OriginalsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OriginalsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OriginalsMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mEFieldButton;
    private javax.swing.JButton oEFLineButton;
    private javax.swing.JButton oEFieldButton;
    // End of variables declaration//GEN-END:variables
}
